services:
  web:
    build: .
    container_name: eventos-comp-back
    ports:
      - "1111:8000"
    volumes:
      - .:/app
    networks:
      - fabrica-network
    
networks:
  fabrica-network:
    external: true